# Run calendar bot (Monday at 12:39 every other week) and birthday_bot (every day at 08:00)

name: scan_bot_calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "39 12 * * 1"

jobs:
  run-scan-bot:
    runs-on: ubuntu-24.04

    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GOOGLE_API_REFRESH_TOKEN: ${{ secrets.GOOGLE_API_REFRESH_TOKEN }}
      GOOGLE_API_CLIENT_ID: ${{ secrets.GOOGLE_API_CLIENT_ID }}
      GOOGLE_API_CLIENT_SECRET: ${{ secrets.GOOGLE_API_CLIENT_SECRET }}

      # Channel id test_bot_channel
      CHANNEL_ID: "C04L70MKXR7"
      # Channel id #scan_department
      # CHANNEL_ID: "C8F6TDG82"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: run calendar bot biweekly
        run: |
          python calendar.py $CHANNEL_ID
