# Run birthday_bot (every day at 06:17)

name: scan_bot_birthday

on:
  workflow_dispatch:
  schedule:
  - cron: '17 6 * * *'

jobs:
  run-scan-bot:
    runs-on: ubuntu-20.04

    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GOOGLE_API_REFRESH_TOKEN: ${{ secrets.GOOGLE_API_REFRESH_TOKEN }}
      GOOGLE_API_CLIENT_ID: ${{ secrets.GOOGLE_API_CLIENT_ID }}
      GOOGLE_API_CLIENT_SECRET: ${{ secrets.GOOGLE_API_CLIENT_SECRET }}

      # Channel id #test_bot_channel on Slack
      CHANNEL_ID: "C04L70MKXR7"
      # Channel id #scan_department on Slack
      # C8F6TDG82

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install build package
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze

      - name: run birthday bot daily 
        run: |
          sh run_birthday_bot.sh $CHANNEL_ID
