# Run calendar bot (Monday at 08:00 every other week) and birthday_bot (every day at 08:00)
name: scan_bot

on:
  schedule:
    - cron: '0 8 1-7,15-21 * 1'
    - cron: '0 8 * * *'

jobs:
  run-scan-bot:
    runs-on: ubuntu-20.04
    env: 
      SLACK_BOT_TOKEN = ${{ secrets.SLACK_BOT_TOKEN }} 
      SLACK_SIGNING_SECRET = ${{ secrets.SLACK_SIGNING_SECRET }}
      GOOGLE_API_TOKEN = ${{ secrets.GOOGLE_API_TOKEN }} 
      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install build package
        run: |
          pip install --upgrade pip
          pip install requirements
          
      - name: run calendar bot biweekly 
        if: github.event.schedule == '0 8 1-7,15-21 * 1'
        run: |
          python.

      - name: run birtday bot daily 
        if: github.event.schedule == '0 8 * * *'
        run: |
          python.

        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
